export type LeaderFeed={statsFetchedAt?:string;leaderboards?:{players?:Record<string,{records:Array<{data:{name:string};team?:{name:string}|null;stat:string|number}>}>}};
export const leaderCategories=[['goals','GOALS'],['assists','ASSISTS'],['average_match_rating','AVG MATCH RATING']];
export function leaderGroups(s:LeaderFeed){return leaderCategories.map(([key,title])=>{const rows=s.leaderboards?.players?.[key]?.records;if(!Array.isArray(rows)||!rows.length||rows.some(r=>!r.data?.name||!Number.isFinite(Number(r.stat))))throw Error('Website category leaders unavailable');return {title,rows:rows.slice(0,5)};});}
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export function leadersSvg(s:LeaderFeed,background:string,leagueName='UNC 6v6 — Season 1',sourceHost='uncfutbolleague.com'){
 const panels=leaderGroups(s).map(({title,rows},col)=>{const x=70+col*520;return `<rect x="${x}" y="230" width="500" height="610" rx="14" fill="#04101e" opacity=".81"/><text x="${x+26}" y="292" fill="#e8c46a" font-size="${col===2?30:40}" font-weight="700">${title}</text>${rows.map((r,n)=>{const y=365+n*93;return `<line x1="${x+26}" x2="${x+474}" y1="${y+30}" y2="${y+30}" stroke="#b8c7d9" opacity=".18"/><text x="${x+26}" y="${y}" fill="#b8c7d9" font-size="25">${n+1}</text><text x="${x+68}" y="${y}" font-size="${r.data.name.length>19?18:23}" font-weight="700">${esc(r.data.name.slice(0,28))}</text><text x="${x+68}" y="${y+27}" fill="#b8c7d9" font-size="16">${esc((r.team?.name||'').slice(0,32))}</text><text x="${x+464}" y="${y}" text-anchor="end" font-size="30" fill="#e8c46a" font-weight="700">${esc(String(r.stat))}</text>`;}).join('')}`;}).join('');
 const date=s.statsFetchedAt&&Number.isFinite(Date.parse(s.statsFetchedAt))?new Date(s.statsFetchedAt).toISOString().replace('T',' ').replace('.000Z',' UTC'):'Unavailable';
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1680" height="960"><defs><linearGradient id="mute" x2="0" y2="1"><stop stop-color="#041326" stop-opacity=".78"/><stop offset=".55" stop-color="#041326" stop-opacity=".48"/><stop offset="1" stop-color="#041326" stop-opacity=".72"/></linearGradient></defs><image href="${esc(background)}" width="1680" height="960" preserveAspectRatio="xMidYMid slice"/><rect width="1680" height="960" fill="url(#mute)"/><g font-family="Arial,sans-serif" fill="white"><text x="70" y="80" fill="#e8c46a" font-size="22" letter-spacing="3">OFFICIAL LEAGUE · UFB</text><text x="70" y="151" font-size="${leagueName.length>30?42:54}" font-weight="700">${esc(leagueName.slice(0,48))} Leaders</text><text x="70" y="194" font-size="24" fill="#b8c7d9">TOP FIVE · OFFICIAL PLAYER STATISTICS</text>${panels}<text x="70" y="914" font-size="19" fill="#b8c7d9">Website stats fetched: ${esc(date)}</text><text x="1610" y="914" text-anchor="end" font-size="19" fill="#e8c46a">${esc(sourceHost)}</text></g></svg>`;
}
