import {fetchLeagueSeason,siteLeagueCommand,type LeagueSource,type Season} from './site-league';
import type {DiscordInteraction,Env} from './types';
import {randomBackground} from './backgrounds';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
const dataUrl=(bytes:Uint8Array,mime:string)=>{let binary='';for(let n=0;n<bytes.length;n+=8192)binary+=String.fromCharCode(...bytes.subarray(n,n+8192));return `data:${mime};base64,${btoa(binary)}`;};
export function standingsSvg(s:Season,background:string,logos:Record<string,string>,leagueName='UNC 6v6 — Season 1',sourceHost='uncfutbolleague.com'){
 const cols=[750,850,950,1050,1160,1270,1380,1510];const headers=['P','W','D','L','GF','GA','GD','PTS'];
 const rows=s.standings.map((r,n)=>{const y=292+n*61;const logo=logos[r[0]];const name=s.teams[r[0]][0];return `<rect x="80" y="${y-36}" width="1520" height="61" fill="${n%2?'#ffffff':'#04101e'}" opacity="${n%2?'.045':'.18'}"/><text x="113" y="${y}" fill="${n<3?'#e8c46a':'#b8c7d9'}">${n+1}</text>${logo?`<image href="${esc(logo)}" x="172" y="${y-33}" width="46" height="46"/>`:`<circle cx="195" cy="${y-10}" r="20" fill="#203854"/>`}<text x="242" y="${y}" font-size="${name.length>25?22:26}">${esc(name.slice(0,40))}</text>${r.slice(1).map((v,k)=>`<text x="${cols[k]}" y="${y}" text-anchor="middle" ${k===7?'fill="#e8c46a" font-weight="700"':''}>${v}</text>`).join('')}`;}).join('');
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1680" height="960" viewBox="0 0 1680 960"><defs><linearGradient id="mute" x2="0" y2="1"><stop stop-color="#041326" stop-opacity=".78"/><stop offset=".55" stop-color="#041326" stop-opacity=".48"/><stop offset="1" stop-color="#041326" stop-opacity=".72"/></linearGradient></defs><image href="${esc(background)}" width="1680" height="960" preserveAspectRatio="xMidYMid slice"/><rect width="1680" height="960" fill="url(#mute)"/><g font-family="Arial,sans-serif" fill="white" font-size="26"><text x="80" y="78" font-size="20" fill="#e8c46a" letter-spacing="3">OFFICIAL LEAGUE · UFB</text><text x="80" y="143" font-size="${leagueName.length>30?42:52}" font-weight="700">${esc(leagueName.slice(0,52))}</text><text x="80" y="184" fill="#cfdae8" font-size="23">OFFICIAL STANDINGS</text><rect x="80" y="215" width="1520" height="660" rx="12" fill="#04101e" opacity=".81"/><rect x="80" y="215" width="1520" height="47" rx="10" fill="#071b36" opacity=".96"/><g font-size="20" font-weight="700" fill="#b8c7d9"><text x="110" y="247">#</text><text x="242" y="247">CLUB</text>${headers.map((h,k)=>`<text x="${cols[k]}" y="247" text-anchor="middle">${h}</text>`).join('')}</g>${rows}<text x="80" y="918" font-size="19" fill="#cfdae8">Source updated: ${esc(new Date(s.syncedAt).toISOString().replace('T',' ').replace('.000Z',' UTC'))} · Latest published website data</text><text x="1600" y="918" text-anchor="end" font-size="19" fill="#e8c46a">${esc(sourceHost)}</text></g></svg>`;
}
async function render(e:Env,s:Season,source:LeagueSource){
 const bg=await e.ASSETS.fetch(`https://assets.local/${randomBackground()}.png`);if(!bg.ok)throw Error('Background unavailable');
 const background=dataUrl(new Uint8Array(await bg.arrayBuffer()),'image/png');const logos:Record<string,string>={};
 await Promise.all(s.standings.map(async r=>{try{const url=new URL(s.teams[r[0]][1]);if(url.protocol!=='https:'||!['ufl.virtualarena.app','www.uncfutbolleague.com','uncfutbolleague.com'].includes(url.hostname))return;const res=await fetch(url,{signal:AbortSignal.timeout(4000)});const mime=res.headers.get('content-type')?.split(';')[0]??'';if(!res.ok||!['image/png','image/jpeg','image/webp'].includes(mime))return;const bytes=new Uint8Array(await res.arrayBuffer());if(bytes.length<1000000)logos[r[0]]=dataUrl(bytes,mime);}catch{/* A missing crest must not prevent standings. */}}));
 const {default:puppeteer}=await import('../runtime/node_modules/@cloudflare/puppeteer/lib/esm/puppeteer/puppeteer-cloudflare.js');const browser=await puppeteer.launch(e.BROWSER);
 try{const page=await browser.newPage();await page.setViewport({width:1680,height:960,deviceScaleFactor:1});await page.setContent(`<html><body style="margin:0">${standingsSvg(s,background,logos,source.name,new URL(source.url).hostname)}</body></html>`);return new Uint8Array(await page.screenshot({type:'png'}));}finally{await browser.close();}
}
export const wantsStandingsImage=(i:DiscordInteraction)=>i.type===2&&i.data?.name==='standings'&&i.data.options?.some(o=>o.name==='league'&&typeof o.value==='string'&&!!o.value);
export async function publishStandingsImage(e:Env,i:DiscordInteraction,source:LeagueSource){
 const endpoint=`https://discord.com/api/v10/webhooks/${i.application_id}/${i.token}/messages/@original`;
 try{const s=await fetchLeagueSeason(source);if(s.standings.length>10)throw Error('Standings table requires pagination');const png=await render(e,s,source);const form=new FormData();form.set('payload_json',JSON.stringify({content:`**${source.name}** · Source updated <t:${Math.floor(Date.parse(s.syncedAt)/1000)}:f>`,allowed_mentions:{parse:[]},attachments:[{id:0,filename:'ufb-standings.png'}]}));form.set('files[0]',new Blob([png.buffer as ArrayBuffer],{type:'image/png'}),'ufb-standings.png');const posted=await fetch(endpoint,{method:'PATCH',body:form,signal:AbortSignal.timeout(10000)});if(!posted.ok)throw Error(`Discord image upload ${posted.status}`);
 }catch(error){console.error('Standings image unavailable',error instanceof Error?error.message:'unknown');const fallback=await siteLeagueCommand(i,source);await fetch(endpoint,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...fallback.data,content:'Image rendering is temporarily unavailable. Here are the website standings instead.',allowed_mentions:{parse:[]}}),signal:AbortSignal.timeout(10000)}).catch(()=>console.error('Standings fallback delivery failed'));}
}
